### ISSUE TITLE
How to config in promethues.yml?

### ISSUE THREAD

**Issue by phyer** [Intrinsec/govc_exporter#1]
Thanks for your working. This project running well in my env as a exporter.  But I do not know how to configure it in promethues.yml. Do you have a sample.yml？

**Comment by ynsta** [comment]
No problem

Here is example of static config:

```yaml
scrape_configs:
  - job_name: "vcenter"
    scrape_interval: 1m
    scrape_timeout: 1m
    static_configs:
      - targets: ["hostname"]
```
